name: On Pull
on:
  pull_request:

jobs:
  test_with_auto_fix:
    runs-on: ubuntu-latest
    name: Test (with auto fix)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run action
        id: test-action
        uses: jacopocarlini/intellij-format-action@main
        with:
          include-glob: '*.kt'
          fail-on-changes: false
          auto-fix: true

